### PR TITLE
Add  Horcrux and flexible install directories

### PR DESCRIPTION
**Pull request by coffeeroaster**
* Allow user installs in non traditional home directories, i.e. /data/user
* Create a horcrux target. This just installs horcrux and a service file. It doesn't configure it.

### CODE REVIEW

**Comment by husonghua** [comment]
Thanks!

**Comment by husonghua** [comment]
@coffeeroaster A few updates:

https://github.com/polkachu/cosmos-validators/commit/6e184a11103ccd372e9094def26e40ba786c1591: This commit overrides two changes from you. 
1. inventory.sample: I believe that you cannot use ansible_facts command in in the inventory file. Besides, this is a sample inventory file, so hard-copying "ubuntu" user is okay since it just provides an example.
2. The 26660 port needs to be open because I force the users to allow prometheus metrics. 9100 needs to be conditionally open if the users choose to install node_exporter. 22 does not need to open here because the ssh port security has been addressed in a companion script https://github.com/polkachu/secure-server-setup. In fact, the script highly recommend that you change the SSH port away from 22 to prevent port sniffing. 

Finally, this commit https://github.com/polkachu/cosmos-validators/commit/70bbeda3c9144d44f23c69e258571093cd102143 updates README to incorporate the Horcrux playbook. 

Thanks for your contribution.

**Comment by coffeeroaster** [comment]
1. inventory.sample:
The "PATH" in the inventory sample does utilize ansible_facts. Just  make sure that the path to ${HOME}/go/bin is set somewhere. 
2.) Ports. Good catch. I personally only allow 26660 and 9100 to specific IPs but I see how this is good for a default out-of-the box setup.

**Comment by husonghua** [comment]
Found an issue with ansible_facts["user_dir"]. When the setting is "become: true" (so it is to enable sudo privilege), ansible_facts["user_dir"] leads to '/root". This leads to rather unpredictable behavior in some scripts. For example, the script of copying the .profile template was intended for /home/<USER> folder but was copied to /root folder. 

Since the goal is to not repeat itself with "/home/{{ ansible_user}}', an easier way to avoid the repetition is to create a new variable "user_dir="/home/{{ ansible_user }}"" in the inventory file. This avoids all repetitions as intended by the ansible_facts command, as we can use {{ user_dir }} throughout the repo. A side benefit is that the Ansible script no longer needs to gather all facts, thus speeding up the execution.

**Comment by husonghua** [comment]
Here is a refactor that reverse some of your codes while keeping the benefits of reducing repetition. https://github.com/polkachu/cosmos-validators/commit/543ee23e61a9f68c0752c22e81c2952f4d58b714

**Pull request merged**
