### PR TITLE
Add networks

### PR DESCRIPTION
**Pull request by dylanschultzie**
@husonghua one important thing to note here is that following our conversation about the prefix, they won't fit your current methodology. 

Signed-off-by: Dylan Schultz <hello@schultzie.dev>

### CODE REVIEW

**Comment by PolkachuIntern** [comment]
Woot woot! 

How can you do custom port prefix like 160? This will make the RPC port as 160657 if we do not revise the other parts of the script. 160657 will not be a valid port.

**Comment by PolkachuIntern** [comment]
By the way, the current prefix system can only run 50-60 chains. Maybe it is time to find a better solution.

**Comment by dylanschultzie** [comment]
@PolkachuIntern

Yeah, so I changed it so the first 3 ports are over-ridden: 

rather than `23` -> `23657` 
I do : `123` -> `12357`

**Comment by PolkachuIntern** [comment]
Thanks!

**Pull request merged**
