### PR TITLE
Create profile.j2

### PR DESCRIPTION
**Pull request by ghost**
Needed for go profile setup

### CODE REVIEW

**Comment by husonghua** [comment]
Thanks for the PR. I incline to reject this PR and PR #8. The horcrux playbook in this repo is supposed to be run on top of the basic setup for for a cosmos node. All of your additions are addressed by the `prepare` role, which can be run independently as the `prepare` playbook and has been integrated in many other playbooks. I do not want to repeat these tasks in the horcrux playbook.

We can argue that these tasks are a perfect fit for an independent repo specifically for horcrox alone. If you want to make such a repo, we will be happy to contribute. Thanks again for the PR.

**Comment by OtterSync** [comment]
I almost put that in the note when I pushed it. Since the readme for
horcrux didn't mention the prepare stage I just sent it over just in case.

**Comment by husonghua** [comment]
Pushed a new commit to improve horcrux documentation: https://github.com/polkachu/cosmos-validators/commit/fcc3aa6814d156694d87d2cb6aec9067cdfb1051

**Comment by PolkachuIntern** [comment]
I am closing this pull request after 1 week. Thanks!

**Pull request closed without merging**
